---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  Devel::PPPort: 3.20
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: B-Size2
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.04
